function alpha_val = alpha_gimbal_func(in1,Ap,Aq,Ar,Ag_p,Ag_q,Ig_x,Ig_y,zeta,xi)
%ALPHA_GIMBAL_FUNC
%    ALPHA_VAL = ALPHA_GIMBAL_FUNC(IN1,Ap,Aq,Ar,Ag_p,Ag_q,Ig_x,Ig_y,ZETA,XI)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-Nov-2025 15:36:40

p = in1(11,:);
q = in1(12,:);
q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
r = in1(13,:);
theta_g = in1(15,:);
xi = in1(17,:);
zeta = in1(16,:);
t2 = cos(theta_g);
t3 = sin(theta_g);
t4 = q.^2;
t5 = q0.^2;
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t9 = r.^2;
t10 = 1.0./zeta;
t11 = t2.*t5;
t12 = t2.*t6;
t13 = t2.*t7;
t14 = t2.*t8;
t15 = q0.*q2.*t3.*2.0;
t16 = q1.*q3.*t3.*2.0;
t17 = -t15;
t18 = -t12;
t19 = -t13;
t20 = t11+t14+t16+t17+t18+t19;
t21 = 1.0./t20;
mt1 = [zeta.*(t4+p.^2);t10.*(Ap.*zeta.*5.0e+3+p.*xi.*2.3e+1-q.*r.*zeta.*2.3e+1).*(-2.0e-4);t10.*(Aq.*zeta.*5.0e+3+q.*xi.*2.3e+1+p.*r.*zeta.*2.3e+1).*(-2.0e-4)];
mt2 = [(t10.*(Ar.*t5.*zeta.*-5.0e+3+Ar.*t6.*zeta.*5.0e+3-Ar.*t7.*zeta.*5.0e+3+Ar.*t8.*zeta.*5.0e+3+q.*q0.*q1.*xi.*9.2e+1-q.*q2.*q3.*xi.*9.2e+1-p.*q.*t5.*zeta.*2.3e+1+p.*q.*t6.*zeta.*2.3e+1-p.*q.*t7.*zeta.*2.3e+1+p.*q.*t8.*zeta.*2.3e+1+q0.*q3.*t4.*zeta.*4.6e+1+q1.*q2.*t4.*zeta.*4.6e+1+q0.*q3.*t9.*zeta.*4.6e+1+q1.*q2.*t9.*zeta.*4.6e+1+p.*q0.*q1.*r.*zeta.*9.2e+1-p.*q2.*q3.*r.*zeta.*9.2e+1))./(t5.*5.0e+3-t6.*5.0e+3+t7.*5.0e+3-t8.*5.0e+3);-t21.*(p.*t5-p.*t6-p.*t7+p.*t8+q0.*q2.*r.*2.0-q1.*q3.*r.*2.0)];
mt3 = [t21.*(-q.*t11+q.*t12+q.*t13-q.*t14+q.*t15+p.*q0.*q1.*t3.*2.0+p.*q2.*q3.*t3.*2.0-q.*q1.*q3.*t3.*2.0+q0.*q1.*r.*t2.*2.0+q2.*q3.*r.*t2.*2.0)];
alpha_val = [mt1;mt2;mt3];
end
