function alpha_val = alpha_drone_func(in1,Ax,Ay,Az,Ap,Aq,Ar)
%ALPHA_DRONE_FUNC
%    ALPHA_VAL = ALPHA_DRONE_FUNC(IN1,Ax,Ay,Az,Ap,Aq,Ar)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-Nov-2025 21:50:28

p = in1(11,:);
q = in1(12,:);
q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
r = in1(13,:);
xi = in1(15,:);
zeta = in1(14,:);
t2 = p.^2;
t3 = q.^2;
t4 = q0.^2;
t5 = q0.^3;
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t9 = q3.^3;
t10 = 1.0./zeta;
et1 = Ar.*t4.^2.*zeta.*5.0e+3+Ar.*t8.^2.*zeta.*5.0e+3+Ar.*t4.*t8.*zeta.*1.0e+4+p.*q2.*t5.*xi.*4.6e+1-p.*q1.*t9.*xi.*4.6e+1-q.*q1.*t5.*xi.*4.6e+1-q.*q2.*t9.*xi.*4.6e+1-p.*q1.*q3.*t4.*xi.*4.6e+1+p.*q0.*q2.*t8.*xi.*4.6e+1-q.*q0.*q1.*t8.*xi.*4.6e+1-q.*q2.*q3.*t4.*xi.*4.6e+1+p.*q.*t4.*t6.*zeta.*2.3e+1-p.*q.*t4.*t7.*zeta.*2.3e+1-p.*q.*t6.*t8.*zeta.*2.3e+1+p.*q.*t7.*t8.*zeta.*2.3e+1-q1.*q2.*t2.*t4.*zeta.*2.3e+1+q1.*q2.*t3.*t4.*zeta.*2.3e+1+q0.*q3.*t2.*t6.*zeta.*2.3e+1-q0.*q3.*t2.*t7.*zeta.*2.3e+1-q0.*q3.*t3.*t6.*zeta.*2.3e+1+q0.*q3.*t3.*t7.*zeta.*2.3e+1+q1.*q2.*t2.*t8.*zeta.*2.3e+1-q1.*q2.*t3.*t8.*zeta.*2.3e+1;
et2 = p.*q.*q0.*q1.*q2.*q3.*zeta.*9.2e+1;
alpha_val = [zeta.*(t2+t3);t10.*(Ap.*zeta.*5.0e+3+p.*xi.*2.3e+1-q.*r.*zeta.*2.3e+1).*(-2.0e-4);t10.*(Aq.*zeta.*5.0e+3+q.*xi.*2.3e+1+p.*r.*zeta.*2.3e+1).*(-2.0e-4);t10.*1.0./(t4+t8).^2.*(et1+et2).*(-2.0e-4)];
end
