function alpha_val = alpha_gimbal_func3(in1,Ap,Aq,Ar,Ag_p,Ag_q,Ag_r,Ix,Iy,Iz,Ig_x,Ig_y,Ig_z,zeta,xi,m)
%ALPHA_GIMBAL_FUNC3
%    ALPHA_VAL = ALPHA_GIMBAL_FUNC3(IN1,Ap,Aq,Ar,Ag_p,Ag_q,Ag_r,Ix,Iy,Iz,Ig_x,Ig_y,Ig_z,ZETA,XI,M)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    16-May-2026 12:29:14

p = in1(11,:);
q = in1(12,:);
q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
r = in1(13,:);
xi = in1(18,:);
zeta = in1(17,:);
t2 = p.^2;
t3 = q.^2;
t4 = 1.0./zeta;
alpha_val = [zeta.*(t2+t3);-t4.*(Ap.*zeta+Ix.*p.*xi.*2.0-Ix.*q.*r.*zeta+Iy.*q.*r.*zeta-Iz.*q.*r.*zeta);-t4.*(Aq.*zeta+Iy.*q.*xi.*2.0-Ix.*p.*r.*zeta+Iy.*p.*r.*zeta+Iz.*p.*r.*zeta);(t4.*(Ar.*q0.*zeta.*-2.0-Iz.*p.*q2.*xi.*4.0+Iz.*q.*q1.*xi.*4.0+Iz.*q3.*t2.*zeta+Iz.*q3.*t3.*zeta+Iz.*q3.*r.^2.*zeta-Ix.*p.*q.*q0.*zeta.*2.0+Iy.*p.*q.*q0.*zeta.*2.0+Iz.*p.*q1.*r.*zeta.*2.0+Iz.*q.*q2.*r.*zeta.*2.0))./(q0.*2.0);0.0;0.0;0.0];
end
