function alpha_val = alpha_func(in1,Ap,Aq,Ar,Ix,Iy,Iz,zeta,xi,m)
%ALPHA_FUNC
%    ALPHA_VAL = ALPHA_FUNC(IN1,Ap,Aq,Ar,Ix,Iy,Iz,ZETA,XI,M)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    10-Nov-2025 20:23:09

p = in1(11,:);
q = in1(12,:);
q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
r = in1(13,:);
xi = in1(15,:);
zeta = in1(14,:);
t2 = q.^2;
t3 = q0.^2;
t4 = q1.^2;
t5 = q2.^2;
t6 = q3.^2;
t7 = r.^2;
t8 = 1.0./zeta;
mt1 = [zeta.*(t2+p.^2);-t8.*(Ap.*zeta+Ix.*p.*xi.*2.0-Ix.*q.*r.*zeta+Iy.*q.*r.*zeta-Iz.*q.*r.*zeta);-t8.*(Aq.*zeta+Iy.*q.*xi.*2.0-Ix.*p.*r.*zeta+Iy.*p.*r.*zeta+Iz.*p.*r.*zeta)];
mt2 = [(t8.*(-Ar.*t3.*zeta+Ar.*t4.*zeta-Ar.*t5.*zeta+Ar.*t6.*zeta+Iz.*q.*q0.*q1.*xi.*4.0-Iz.*q.*q2.*q3.*xi.*4.0-Ix.*p.*q.*t3.*zeta+Ix.*p.*q.*t4.*zeta-Ix.*p.*q.*t5.*zeta+Ix.*p.*q.*t6.*zeta+Iy.*p.*q.*t3.*zeta-Iy.*p.*q.*t4.*zeta+Iy.*p.*q.*t5.*zeta-Iy.*p.*q.*t6.*zeta-Iz.*p.*q.*t3.*zeta+Iz.*p.*q.*t4.*zeta-Iz.*p.*q.*t5.*zeta+Iz.*p.*q.*t6.*zeta+Iz.*q0.*q3.*t2.*zeta.*2.0+Iz.*q1.*q2.*t2.*zeta.*2.0+Iz.*q0.*q3.*t7.*zeta.*2.0+Iz.*q1.*q2.*t7.*zeta.*2.0+Iz.*p.*q0.*q1.*r.*zeta.*4.0-Iz.*p.*q2.*q3.*r.*zeta.*4.0))./(t3-t4+t5-t6)];
alpha_val = [mt1;mt2];
end
