function alpha_val = alpha_func(in1,Ix,Iy,Iz,m)
%ALPHA_FUNC
%    ALPHA_VAL = ALPHA_FUNC(IN1,Ix,Iy,Iz,M)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    10-Nov-2025 16:25:31

p = in1(11,:);
q = in1(12,:);
q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
r = in1(13,:);
xi = in1(15,:);
zeta = in1(14,:);
t2 = q.^2;
t3 = q0.^2;
t4 = q1.^2;
t5 = q2.^2;
t6 = q3.^2;
t7 = r.^2;
t8 = 1.0./zeta;
mt1 = [zeta.*(t2+p.^2);-t8.*(Ix.*p.*xi.*2.0-Ix.*q.*r.*zeta+Iy.*q.*r.*zeta-Iz.*q.*r.*zeta);-t8.*(Iy.*q.*xi.*2.0-Ix.*p.*r.*zeta+Iy.*p.*r.*zeta+Iz.*p.*r.*zeta)];
mt2 = [(t8.*(-Iz.*t2.*t3.*zeta-Iz.*t2.*t4.*zeta+Iz.*t2.*t5.*zeta+Iz.*t2.*t6.*zeta-Iz.*t3.*t7.*zeta-Iz.*t4.*t7.*zeta+Iz.*t5.*t7.*zeta+Iz.*t6.*t7.*zeta+Iz.*q.*q0.*q2.*xi.*4.0+Iz.*q.*q1.*q3.*xi.*4.0-Ix.*p.*q.*q0.*q3.*zeta.*2.0+Ix.*p.*q.*q1.*q2.*zeta.*2.0+Iy.*p.*q.*q0.*q3.*zeta.*2.0-Iy.*p.*q.*q1.*q2.*zeta.*2.0-Iz.*p.*q.*q0.*q3.*zeta.*2.0+Iz.*p.*q.*q1.*q2.*zeta.*2.0+Iz.*p.*q0.*q2.*r.*zeta.*4.0+Iz.*p.*q1.*q3.*r.*zeta.*4.0))./(q0.*q3.*2.0-q1.*q2.*2.0)];
alpha_val = [mt1;mt2];
end
