function beta_val = beta_gimbal_func(in1,Ap,Aq,Ar,Ag_p,Ag_q,Ix,Iy,Iz,Ig_x,Ig_y,zeta,xi,m)
%BETA_GIMBAL_FUNC
%    BETA_VAL = BETA_GIMBAL_FUNC(IN1,Ap,Aq,Ar,Ag_p,Ag_q,Ix,Iy,Iz,Ig_x,Ig_y,ZETA,XI,M)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Nov-2025 19:30:46

q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
zeta = in1(16,:);
t2 = q0.*q1;
t3 = q0.*q2;
t4 = q0.*q3;
t5 = q1.*q2;
t6 = q1.*q3;
t7 = q2.*q3;
t8 = q0.^2;
t9 = q1.^2;
t10 = q2.^2;
t11 = q3.^2;
t12 = 1.0./zeta;
t13 = -t9;
t14 = -t10;
t15 = -t11;
t16 = t8+t9+t10+t11;
t17 = 1.0./t16.^2;
t18 = t8+t10+t13+t15;
t19 = t18./(t18.^2 + 0.001);
beta_val = reshape([m.*t17.*(t3+t6).*2.0,Ix.*m.*t12.*t17.*(t4-t5).*2.0,Iy.*m.*t12.*t17.*(t8+t9+t14+t15),Iz.*m.*t12.*t17.*t19.*(t3.*t4-t2.*t8+t5.*t6+t2.*t10+t2.*t11+t2.*t13+t7.*t14+t7.*t15).*2.0,0.0,0.0,m.*t17.*(t2-t7).*-2.0,-Ix.*m.*t12.*t17.*t18,Iy.*m.*t12.*t17.*(t4+t5).*2.0,Iz.*m.*t12.*t17.*t19.*(t2.*t4+t2.*t5-t5.*t7+t3.*t15).*-4.0,0.0,0.0,m.*t17.*(t8+t11+t13+t14),Ix.*m.*t12.*t17.*(t2+t7).*-2.0,Iy.*m.*t12.*t17.*(t3-t6).*-2.0,Iz.*m.*t12.*t17.*t19.*(t2.*t3-t2.*t6-t3.*t7+t5.*t11).*4.0,0.0,0.0,0.0,0.0,0.0,Iz.*t19,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,6]);
end
