function beta_val = beta_gimbal_func3(in1,Ap,Aq,Ar,Ag_p,Ag_q,Ag_r,Ix,Iy,Iz,Ig_x,Ig_y,Ig_z,zeta,xi,m)
%BETA_GIMBAL_FUNC3
%    BETA_VAL = BETA_GIMBAL_FUNC3(IN1,Ap,Aq,Ar,Ag_p,Ag_q,Ag_r,Ix,Iy,Iz,Ig_x,Ig_y,Ig_z,ZETA,XI,M)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    16-May-2026 12:29:14

q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
zeta = in1(17,:);
t2 = q0.*q1;
t3 = q0.*q2;
t4 = q0.*q3;
t5 = q1.*q2;
t6 = q1.*q3;
t7 = q2.*q3;
t8 = q0.^2;
t9 = q1.^2;
t10 = q2.^2;
t11 = q3.^2;
t12 = 1.0./q0;
t13 = 1.0./zeta;
t14 = -t9;
t15 = -t10;
t16 = -t11;
t17 = t8+t9+t10+t11;
t18 = 1.0./t17.^2;
beta_val = reshape([m.*t18.*(t3+t6).*2.0,Ix.*m.*t13.*t18.*(t4-t5).*2.0,Iy.*m.*t13.*t18.*(t8+t9+t15+t16),-Iz.*m.*t12.*t13.*t18.*(q0.*t2-q3.*t3.*2.0+q2.*t5-q3.*t6+q1.^3),0.0,0.0,0.0,m.*t18.*(t2-t7).*-2.0,-Ix.*m.*t13.*t18.*(t8+t10+t14+t16),Iy.*m.*t13.*t18.*(t4+t5).*2.0,-Iz.*m.*t12.*t13.*t18.*(q0.*t3+q3.*t2.*2.0+q1.*t5-q3.*t7+q2.^3),0.0,0.0,0.0,m.*t18.*(t8+t11+t14+t15),Ix.*m.*t13.*t18.*(t2+t7).*-2.0,Iy.*m.*t13.*t18.*(t3-t6).*-2.0,Iz.*m.*q3.*t12.*t13.*t18.*(t9+t10).*-2.0,0.0,0.0,0.0,0.0,0.0,0.0,Iz.*t12.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[7,7]);
end
