function beta_val = beta_func(in1,Ix,Iy,Iz,m)
%BETA_FUNC
%    BETA_VAL = BETA_FUNC(IN1,Ix,Iy,Iz,M)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    10-Nov-2025 16:25:32

q0 = in1(4,:);
q1 = in1(5,:);
q2 = in1(6,:);
q3 = in1(7,:);
zeta = in1(14,:);
t2 = q0.*q1;
t3 = q0.*q2;
t4 = q0.*q3;
t5 = q1.*q2;
t6 = q1.*q3;
t7 = q2.*q3;
t8 = q0.^2;
t9 = q1.^2;
t10 = q2.^2;
t11 = q3.^2;
t12 = 1.0./zeta;
t13 = -t5;
t14 = -t6;
t15 = -t9;
t16 = -t10;
t17 = -t11;
t18 = t3+t6;
t19 = t4+t5;
t23 = t8+t9+t10+t11;
t20 = t3+t14;
t21 = t4+t13;
t24 = 1.0./t23.^2;
t25 = t8+t9+t16+t17;
t22 = 1.0./t21;
beta_val = reshape([m.*t18.*t24.*2.0,Ix.*m.*t12.*t21.*t24.*2.0,Iy.*m.*t12.*t24.*t25,-Iz.*m.*t12.*t18.*t22.*t24.*t25,m.*t24.*(t2-t7).*-2.0,-Ix.*m.*t12.*t24.*(t8+t10+t15+t17),Iy.*m.*t12.*t19.*t24.*2.0,Iz.*m.*t12.*t18.*t19.*t22.*t24.*-2.0,m.*t24.*(t8+t11+t15+t16),Ix.*m.*t12.*t24.*(t2+t7).*-2.0,Iy.*m.*t12.*t20.*t24.*-2.0,Iz.*m.*t12.*t18.*t20.*t22.*t24.*2.0,0.0,0.0,0.0,Iz.*t22.*(-1.0./2.0)],[4,4]);
end
